[supervisord]
nodaemon=true
logfile=/opt/run/supervisord.conf
loglevel=debug

[program:tigervnc]
command=/usr/lib/x86_64-linux-gnu/tigervncserver :1
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:novnc]
command=/opt/run/novnc/utils/websockify/run --web /opt/run/novnc 8080 [::1]:5901
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:user_command]
command=/opt/run/user_command.sh
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
