[supervisord]
nodaemon=true
loglevel=debug

[program:tigervnc]
command=/usr/lib/x86_64-linux-gnu/tigervncserver :1
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
user=novnc_user
environment=HOME="/home/novnc_user",USER="novnc_user"
directory=/home/novnc_user

[program:novnc]
command=/root/novnc/utils/websockify/run --web /root/novnc 8080 [::1]:5901
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:user_command]
command=/home/novnc_user/user_command.sh
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
user=novnc_user
environment=HOME="/home/novnc_user",USER="novnc_user"
directory=/home/novnc_user
