name: nxv
channels:
  - conda-forge
  - mantid/label/nightly
  - oncat
dependencies:
  - python>=3.11
  - numpy
  - scipy
  - matplotlib
  - pycifrw
  - h5py
  - pyvista>=0.45.2
  - pyvistaqt
  - qtpy
  - vtk
  - pytest
  - mantid
  - scikit-learn
  - scikit-image
  - astropy
  - dill
  - psutil
  - qdarkstyle
  - qtawesome
  - multiprocess
  - black
  - sphinx
  - sphinx-autodoc-typehints
  - pydata-sphinx-theme
  - numpydoc
  - pre-commit
  - pip:
    - pyoncat
