beamlines = {
    "SNAP": {
        "Name": "SNAP",
        "InstrumentName": "SNAP",
        "Facility": "SNS",
        "Wavelength": [0.6, 3.7],
        "MinD": 0.7,
        "Grouping": "2x2",
        "BankPixels": [256, 256],
        "MaskEdges": [16, 16],
        "MaskBanks": [],
        "Goniometers": [
            "BL3:Mot:omega,0,1,0,1",
            "BL3:Mot:chi,0,0,1,1",
            "BL3:Mot:phi,0,1,0,1",
        ],
        "Goniometer": {
            "chi-45": {
                "BL3:Mot:omega": [0, 1, 0, 1, -180, 180],
                "BL3:Mot:phi": [0.70710678, 0.70710678, 0, 1, -180, 180],
            },
            "chi-0": {
                "BL3:Mot:omega": [0, 1, 0, 1, -180, 180],
                "BL3:Mot:phi": [0, 1, 0, 1, -180, 180],
            },
        },
        "GoniometerNames": "ω,χ,φ",
        "Motor": {
            "det_lin1": 0,
            "det_lin2": 0,
            "det_arc1": -65,
            "det_arc2": 105,
        },
        "RawFile": "nexus/SNAP_{}.nxs.h5",
        "Counting": ["BL3:Det:PCharge:C", "seconds"],
        "Title": "BL3:SMS:RunInfo:RunTitle",
    },
    "CORELLI": {
        "Name": "CORELLI",
        "InstrumentName": "CORELLI",
        "Facility": "SNS",
        "Wavelength": [0.6, 2.5],
        "MinD": 0.7,
        "Grouping": "1x4",
        "BankPixels": [16, 256],
        "MaskEdges": [0, 16],
        "MaskBanks": [1, 2, 3, 4, 5, 6, 29, 30, 62, 63, 64, 65, 66, 67, 91],
        "MaskLost": [[58, [13, 16], [80, 130]], [59, [1, 4], [80, 130]]],
        "Goniometers": [
            "BL9:Mot:Sample:Axis1,0,1,0,1",
            "BL9:Mot:Sample:Axis2,0,1,0,1",
            "BL9:Mot:Sample:Axis3,0,1,0,1",
        ],
        "Goniometer": {
            "Goniometer": {
                "BL9:Mot:Sample:Axis1": [0, 1, 0, 1, 0, 0],
                "BL9:Mot:Sample:Axis2": [0, 1, 0, 1, 0, 0],
                "BL9:Mot:Sample:Axis3": [0, 1, 0, 1, 0, 360],
            }
        },
        "GoniometerNames": "ω,χ,φ",
        "RawFile": "nexus/CORELLI_{}.nxs.h5",
        "Counting": ["BL9:Det:PCharge:C", "seconds"],
        "Title": "BL9:SMS:RunInfo:RunTitle",
    },
    "TOPAZ": {
        "Name": "TOPAZ",
        "InstrumentName": "TOPAZ",
        "Facility": "SNS",
        "Wavelength": [0.4, 3.5],
        "MinD": 0.7,
        "Grouping": "2x2",
        "BankPixels": [256, 256],
        "MaskEdges": [16, 16],
        "MaskBanks": [],
        "Goniometers": [
            "BL12:Mot:omega,0,1,0,1",
            "BL12:Mot:chi,0,0,1,1",
            "BL12:Mot:phi,0,1,0,1",
        ],
        "Goniometer": {
            "Ambient": {
                "BL12:Mot:goniokm:omega": [0, 1, 0, 1, -180, 180],
                "BL12:Mot:goniokm:chi": [0, 0, 1, 1, 135, 135],
                "BL12:Mot:goniokm:phi": [0, 1, 0, 1, -180, 180],
            },
            "Cryogenic": {
                "BL12:Mot:Gonioc:Omega": [0, 1, 0, 1, -180, 180],
                "BL12:Mot:Gonioc:Chi": [0, 0, 1, 1, 0, 0],
                "BL12:Mot:Gonioc:Phi": [0, 1, 0, 1, 0, 0],
            },
        },
        "GoniometerNames": "ω,χ,φ",
        "RawFile": "nexus/TOPAZ_{}.nxs.h5",
        "Counting": ["BL12:Det:PCharge:C", "seconds"],
        "Title": "BL12:SMS:RunInfo:RunTitle",
    },
    "MANDI": {
        "Name": "MANDI",
        "InstrumentName": "MANDI",
        "Facility": "SNS",
        "Wavelength": [2, 4],
        "MinD": 2.0,
        "Grouping": "2x2",
        "BankPixels": [256, 256],
        "MaskEdges": [16, 16],
        "MaskBanks": [],
        "Goniometers": [
            "BL11B:Mot:omega,0,1,0,1",
            "BL11B:Mot:chi,0,0,1,1",
            "BL11B:Mot:phi,0,1,0,1",
        ],
        "Goniometer": {
            "Goniometer": {
                "BL11B:Mot:omega": [0, 1, 0, 1, 0, 90],
                "BL11B:Mot:chi": [0, 0, 1, 1, 130, 130],
                "BL11B:Mot:phi": [0, 1, 0, 1, -180, 180],
            }
        },
        "GoniometerNames": "ω,χ,φ",
        "RawFile": "nexus/MANDI_{}.nxs.h5",
        "Counting": ["BL11B:Det:PCharge:C", "seconds"],
        "Title": "BL11B:SMS:RunInfo:RunTitle",
    },
    "IMAGINE": {
        "Name": "IMAGINE",
        "InstrumentName": "CG4D",
        "Facility": "HFIR",
        "Wavelength": [2, 4.5],
        "MinD": 2.0,
        "Grouping": "4x4",
        "BankPixels": [512, 512],
        "MaskEdges": [32, 32],
        "MaskBanks": [],
        "Goniometers": [
            "CG4D:Mot:omega,0,1,0,1",
            "CG4D:Mot:alpha,0,0,1,1",
            "CG4D:Mot:kappa,0,1,0,1",
            "CG4D:Mot:beta,0,0,1,1",
            "CG4D:Mot:phi,0,1,0,1",
        ],
        "Goniometer": {
            "Goniometer": {
                "CG4D:Mot:omega": [0, 1, 0, 1, -180, 180],
                "CG4D:Mot:alpha": [0, 0, 1, 1, 45, 45],
                "CG4D:Mot:kappa": [0, 1, 0, 1, -180, 180],
                "CG4D:Mot:beta": [0, 0, 1, 1, -45, -45],
                "CG4D:Mot:phi": [0, 1, 0, 1, -180, 180],
            }
        },
        "GoniometerNames": "ω,κ,φ",
        "RawFile": "nexus/CG4D_{}.nxs.h5",
        "Counting": ["seconds"],
        "Title": "CG4D:SMS:RunInfo:RunTitle",
    },
    "WAND²": {
        "Name": "WAND",
        "InstrumentName": "HB2C",
        "Facility": "HFIR",
        "Wavelength": 1.486,
        "MinD": 0.7,
        "Grouping": "4x4",
        "BankPixels": [480, 512],
        "MaskEdges": [0, 16],
        "MaskBanks": [],
        "Goniometers": ["s1,0,1,0,1"],
        "Goniometer": {
            "Goniometer": {
                "HB2C:Mot:sgl": [1, 0, 0, -1, 0, 0],
                "HB2C:Mot:sgu": [0, 0, 1, -1, 0, 0],
                "HB2C:Mot:s1": [0, 1, 0, 1, -180, 180],
            }
        },
        "Motor": {
            "HB2C:Mot:s2.RBV": 30,
            "HB2C:Mot:detz.RBV": 0,
        },
        "GoniometerNames": "l,u,s1",
        "RawFile": "nexus/HB2C_{}.nxs.h5",
        "Counting": ["seconds"],
        "Title": "HB2C:SMS:RunInfo:RunTitle",
    },
    "DEMAND": {
        "Name": "HB3A",
        "InstrumentName": "HB3A",
        "Facility": "HFIR",
        "Wavelength": 1.546,
        "MinD": 0.7,
        "Grouping": "4x4",
        "BankPixels": [512, 512],
        "MaskEdges": [32, 32],
        "MaskBanks": [],
        "Goniometers": [
            "omega,0,1,0,-1",
            "chi,0,0,1,-1",
            "phi,0,1,0,-1",
        ],
        "Goniometer": {
            "Goniometer": {
                "omega": [0, 1, 0, -1, -13, 45],
                "chi": [0, 0, 1, -1, -91, 91],
                "phi": [0, 1, 0, -1, -180, 180],
            }
        },
        "Motor": {
            "2theta": 30,
            "det_trans": 410.38595,
        },
        "GoniometerNames": "ω,χ,φ",
        "RawFile": "shared/autoreduce/HB3A_exp{:04}_scan{:04}.nxs",
        "Counting": ["seconds"],
        "Title": "Title",
    },
}
